### ISSUE TITLE
React Native 0.58.3 issue: undefined is not an object (evaluating '_reactNative.Modal.propTypes.animationType')

### ISSUE THREAD

**Issue by DanielDanaee** [peacechen/react-native-modal-selector#100]
### **Following error pops up right after i upgraded my project to React Native 0.58.3**

`undefined is not an object (evaluating '_reactNative.Modal.propTypes.animationType')
<unknown>
    index.js:33:52
loadModuleImplementation
    require.js:321:6
guardedLoadModule
    require.js:207:36
metroRequire
    require.js:127:24
<unknown>
    EventFilters.js:12
loadModuleImplementation
    require.js:321:6
guardedLoadModule
    require.js:207:36
metroRequire
    require.js:127:24
<unknown>
    Events.js:25
loadModuleImplementation
    require.js:321:6
guardedLoadModule
    require.js:207:36
metroRequire
    require.js:127:24
<unknown>
    HomeRoutes.js:15
loadModuleImplementation
    require.js:321:6
guardedLoadModule
    require.js:207:36
metroRequire
    require.js:127:24
<unknown>
    AuthRouter.js:19
loadModuleImplementation
    require.js:321:6
guardedLoadModule
    require.js:207:36
metroRequire
    require.js:127:24
<unknown>
    App.js:7
loadModuleImplementation
    require.js:321:6
guardedLoadModule
    require.js:207:36
metroRequire
    require.js:127:24
<unknown>
    index.js:4
loadModuleImplementation
    require.js:321:6
guardedLoadModule
    require.js:199:45
metroRequire
    require.js:127:24
global code`

### commenting these lines at 
./node_modules/react-native-modal-selector/index.js:52
./node_modules/react-native-modal-selector/index.js:33

**Comment by peacechen** [comment]
Thanks @DanielDanaee for the heads up.  FB deprecated the Modal prop types so we'll need to transition to the prop-types library.  Most of the other prop types have already been migrated over.

I'll try to find some time to fix this.  If anyone wants to submit a PR, I'll merge and cut a release promptly.

**Comment by DanielDanaee** [comment]
Thanks alot!
