### ISSUE TITLE
How can I put an icon inside the touchable area?

### ISSUE THREAD

**Issue by Aequitas737** [peacechen/react-native-modal-selector#105]
Currently I've got:

```
            <ModalSelector
                ...props
            >
                <View>
                     <Icon
                        name="arrow-drop-down"
                        size={22}
                        color='gray'
                    />
                </View>
            </ModalSelector>
```

But the icon is not clickable, there doesn't seem to be a prop where I can pass in an icon, am I missing it? or how would you go about accomplishing this?

**Comment by peacechen** [comment]
At first glance that seems like it should work.  Maybe there's an issue with the Icon nested inside a View?  Try removing it which would give you this:
```
    <ModalSelector
        ...props
    >
        <Icon
            name="arrow-drop-down"
            size={22}
            color='gray'
        />
    </ModalSelector>
```

If that works, and you really need a containing View, wrap that entire block inside a View (around the ModalSelector).

**Comment by Aequitas737** [comment]
Thanks for your response @peacechen unfortunately that also produces the same result.

This is what I've got now, I even removed all other styling that I had on the ModalSelector.
```
            <ModalSelector
                data={this.state.items}
                initValue={initValue}
                onChange={item => this.props.onSelect(item.value)}
                cancelText='Cancel'
            >
                <Icon
                    name="arrow-drop-down"
                    size={22}
                    color='gray'
                />
            </ModalSelector>
```

A strange thing is that if I click on the element, then a press effect appears over the icon (but the icon itself is unclickable, also the dropdown that appears is only as wide as the clickable area)

**Comment by peacechen** [comment]
It could be a peculiarity with the RN and the Icon library you're using.  If you replace it with a View, is it touchable?

**Comment by Aequitas737** [comment]
Ah my apologies, there was code elsewhere that was affecting the styling and I didn't notice.
