### ISSUE TITLE
Generate list from API

### ISSUE THREAD

**Issue by sakshamsd** [peacechen/react-native-modal-selector#108]
How do I generate the ArrayList from API to set in the modal??

**Comment by mikaello** [comment]
Hi

This dependence on how you get your data and how it is formatted. The requirement for this module is that you create a data array of objects conforming to this structure (it could also have additional fields, but at least these):

```typescript
{ key: string | number, label: string | number }
```

The property name `key` must be unique, and is kind of the ID for each of the data elements, while `label` is what is actually shown in the user interface when using the `react-native-modal-selector`-component.

Look at the example in the [readme](https://github.com/peacechen/react-native-modal-selector/blob/master/README.md) to see how this will look like when actually used with the component, or clone this repo and run [the sample app](https://github.com/peacechen/react-native-modal-selector/tree/master/SampleApp).

How you end up with the data array is up to you.
