### ISSUE TITLE
How to change color of the horizontal divider between options in modal?

### ISSUE THREAD

**Issue by buffaloDeveloper** [peacechen/react-native-modal-selector#109]
Not sure which style property needs to be updated.

**Comment by peacechen** [comment]
Try `sectionStyle` and/or `sectionTextStyle`

**Comment by averyvery** [comment]
If you're just changing options, I think it's `borderBottomColor` on the `optionStyle` prop. If you have sections, you'll need to set this on `sectionStyle` as well.

**Comment by zubbey** [comment]
Thanks @averyvery
