### ISSUE TITLE
undefined is not an object (evaluation '_reactNative.Modal.propTypes.animationType')

### ISSUE THREAD

**Issue by russellborja** [peacechen/react-native-modal-selector#121]
I upgraded my Expo SDK to version 35.0.0 which in turn upgrades react-native to 0.59.0. I believe the latest version of `react-native-modal-selector` is incompatible with this version of react-native. I get the error below when I try to `expo start` :
![image](https://user-images.githubusercontent.com/5522156/66725241-e66e2e00-edfd-11e9-99df-92968d374fdf.png)

My package.json is as follows:
```{
  "name": "WizardScores",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "jest-expo": "^35.0.0",
    "react-test-renderer": "16.3.1"
  },
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "eject": "expo eject",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^35.0.0",
    "immutability-helper": "^2.7.1",
    "lodash.clonedeep": "^4.5.0",
    "lodash.range": "^3.2.0",
    "prop-types": "^15.6.2",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-modal-selector": "^1.1.1",
    "react-navigation": "^2.12.1"
  }
}
```

Has anyone encountered or resolved this issue before? Thanks

**Comment by mikaello** [comment]
Are you sure this is fault of `react-native-modal-selector`? And that you have the latest versions actually installed in `node_modules` (e.g. if you `cat node_modules/react-native-modal-selector/package.json`, is it `v1.1.1` that is installed?).

This problem should have been fixed in an earlier PR: https://github.com/peacechen/react-native-modal-selector/pull/99

**Comment by russellborja** [comment]
Maybe I had a cached copy of the old version, I reloaded it with `v1.1.1` and it works fine now!
