### ISSUE TITLE
Fire an event when users click on cancel button

### ISSUE THREAD

**Issue by tannguyen16** [peacechen/react-native-modal-selector#128]
Hi peacechen, thanks for the repo! 

Would there be a way to fire an event when users click on the Cancel button only? Since onChange would not handle the Cancel button. If not, can I add an onDismiss event for this?

Thank you.

**Comment by mikaello** [comment]
You got the `onModalClose` prop, could that suffice?

**Comment by tannguyen16** [comment]
Hi @mikaello, I tried using onModalClose but I think it has a short delay, which fires before the modal completely closing and before the onChange event finishing.
 
For example, I set the onModalClose event to display the error message if nothing changes and set the onChange event to show the success message. Then the app would display the error message for a very short time then show the success message.
