### ISSUE TITLE
eslint

### ISSUE THREAD

**Issue by fabriziomoscon** [peacechen/react-native-modal-selector#13]
I would like to add a `.eslintrc` file and a lint pre-commit process for each contribution.

In this way:
- all changes adhere to library code and style standards
- we can avoid future debates in PRs
- the code will be more readable and each contributor will have clear rules for formatting and code style.

I would like to use the latest packages:
`eslint: 4.4.1`

some popular react-native repo's which I would like to evaluate for adoption:
- react-native rules: https://github.com/facebook/react-native/blob/master/.eslintrc
- react-native-vector-icon: https://github.com/oblador/react-native-vector-icons/blob/master/.eslintrc
- react-native-maps: https://github.com/airbnb/react-native-maps/blob/master/.eslintrc

### existing rules (inferred by looking at the style)
- "indent": [2, 4]
- use semicons

anyone against it?

**Comment by peacechen** [comment]
eslint is a good idea.  Thanks for the PR!

I'm a fan of allowing trailing commas in objects and arrays.  It's not syntactic JS, but it reduces runtime errors when modifying objects (e.g. missing a comma in a middle entry).  What are your thoughts about that?

**Comment by fabriziomoscon** [comment]
yes I completely agree. I will add the rule as part of the second commit

**Comment by mvanroon** [comment]
did you know that eslint cli also allows for automatic fixing of complete files based on the current .eslintrc

https://eslint.org/docs/user-guide/command-line-interface#--fix
