### ISSUE TITLE
Can't disable specific options

### ISSUE THREAD

**Issue by ssghajar** [peacechen/react-native-modal-selector#130]
Hi peacechen, thanks for the repo!
is it possible to style and disable specific option boxes?

**Comment by peacechen** [comment]
Yes the `component` key in each data object allows you to pass in any component you like.
https://github.com/peacechen/react-native-modal-selector#data-format

**Comment by ssghajar** [comment]
> Yes the `component` key in each data object allows you to pass in any component you like.
> https://github.com/peacechen/react-native-modal-selector#data-format

Thank you so much 🙏🏻
