### ISSUE TITLE
move style.js inside index.js

### ISSUE THREAD

**Issue by fabriziomoscon** [peacechen/react-native-modal-selector#14]
I would like to move `style.js` inside `index.js`.
Having it in a separate file doesn't add anything extra because:
- it is not reused in any other files
- the library is very small and all the style are applied to `ModalSelector`
- I think it would make it easier the development process and the debugging from user that just have a peak from under node_modules

anyone against it?

**Comment by peacechen** [comment]
While I'm also a proponent of simplicity, a monolithic file is counter productive for development.  As the project becomes more complex, a long single file is harder read and more difficult to optimize.  Styles in particular are a good separation of functionality for a separate file.  This also allows changes to a separate style file without polluting the code.

**Comment by fabriziomoscon** [comment]
yes it's a trade-off,
the way I see it having a separate file is good for development (when there are many people contributing and the files get long)
but for users that want to take a look from the installed node_modules directory it is painful having the default style props in index.js and the relative style in a separate sheet.

Anyway I am happy to keep it separately.
