### ISSUE TITLE
Set showsVerticalScrollIndicator to false on scrollview

### ISSUE THREAD

**Issue by ticholNyler** [peacechen/react-native-modal-selector#147]
I dont see any props for the scrollview besides the accessibility stuff. Can I hide the scrollbar?

**Comment by peacechen** [comment]
Not at the moment.  This has been requested previously and should be straight-forward to add.
https://github.com/peacechen/react-native-modal-selector/issues/146#issuecomment-634220000

This is a community supported library and your contributions are welcome. Please submit a PR and I'll review promptly.
