### ISSUE TITLE
Add a close() type to the ModalSelector class

### ISSUE THREAD

**Issue by jurajzsiga** [peacechen/react-native-modal-selector#176]
`open` and `getSelectedItem` types are provided in the `ModalSelector` class, but a type for `close` is missing. 

Not a huge issue of course as I am extending the type in my custom component (although I am not sure what the args are) 🙂  but it would be nice to have it out of the box for TS support.

**Comment by mikaello** [comment]
Thanks for the suggestion. Added in `react-native-modal-selector@2.1.1`.
