### ISSUE TITLE
Let user decide which animation to use for displaying modal

### ISSUE THREAD

**Issue by mikaello** [peacechen/react-native-modal-selector#18]
Proposal: `propTypes.animationType`, optional prop that could be set to either `none`, `fade`, or `slide`, with `slide` as default (as today).

**Comment by mvanroon** [comment]
Perhaps even a different animation for the backdrop. A common pattern for iOS pickers is that the backdrop fades in and the picker slides in from the bottom

![picker](https://user-images.githubusercontent.com/1309448/30022596-425ac804-916c-11e7-970e-99634fbb3a42.gif)

**Comment by mikaello** [comment]
I like your idea for future development of this animation.
