### ISSUE TITLE
I can _almost_ custom every styles

### ISSUE THREAD

**Issue by drpiou** [peacechen/react-native-modal-selector#19]
Hi,

I choose your plugin because it's easily customisable, but I needed to custom the options wrapper and there is no such prop for that.

I replaced (with the "propTypes" and "defaultProps"):
`{styles.optionContainer}`
by:
`{[styles.optionContainer, this.props.optionContainerStyle]}`

My question is:
can you please add this feature?

Thanks in advance

P.S: Maybe two `this.props.optionFirstStyle` and `this.props.optionLastStyle` could also be interesting (eg: remove last option borderBottom).

**Comment by peacechen** [comment]
That's a useful proposal, and I believe one of the other threads may have touched on that.  Please submit a PR and one of us will merge it.

**Comment by tonygriv** [comment]
Please, update version in npm

**Comment by peacechen** [comment]
Publish v0.0.18 to npm.
