### ISSUE TITLE
Value Property

### ISSUE THREAD

**Issue by matteo-pennisi** [peacechen/react-native-modal-selector#2]
By default data need to be formatted in this way:
```const data = [
            { key: index++,  label: 'Fruits' },
            { key: index++, label: 'Red Apples' },
            { key: index++, label: 'Cherries' },
            { key: index++, label: 'Cranberries' },
```
I really need a value property like [React Native Picker](https://facebook.github.io/react-native/docs/picker.html). For example input data will be:
```const data = [
            { key: index++,  label: 'Fruits', value: 'fruit1' },
            { key: index++, label: 'Red Apples', value: 'fruit5' },
            { key: index++, label: 'Cherries',value: 'fruit3'},
            { key: index++, label: 'Cranberries',value: 'fruit11' },
```
How I can do this?

**Comment by peacechen** [comment]
Hi @matteo-pennisi 

Do you have a PR that you'd like to merge?  How should the label and value keys behave?  I'm guessing that selecting an item includes the value?

**Comment by matteo-pennisi** [comment]
Oh sorry my bad. I just added a custom value and call it from option.value and now everything works.
Anyway thanks for the support. Keep it going with this repo :smile:
