### ISSUE TITLE
Organize props in readme as a table

### ISSUE THREAD

**Issue by mikaello** [peacechen/react-native-modal-selector#23]
I think the list of props would be more easy to follow as a table rather than a list. An example of this is how [react-native-modal-dropdown](https://github.com/sohobloo/react-native-modal-dropdown#props) have organized their props, this module have the same header/categories.

**Comment by peacechen** [comment]
Good suggestion.  I'll update the Readme along with a few other minor edits that have been outstanding.

**Comment by peacechen** [comment]
Updated Readme in commit 0a48df1055e6ab68e8b249175059f0eba51a5bce

**Comment by mikaello** [comment]
Good call!
