### ISSUE TITLE
selectTextStyle has wrong propTypes

### ISSUE THREAD

**Issue by mienaikoe** [peacechen/react-native-modal-selector#25]
If you set `textAlign` or `color` on the selectTextStyle prop, you get a warning:

Failed prop type: Invalid props.selectTextStyle key 'color' supplied to 'ModalSelector'.

I looked into the source code, and found that index.js:29 has this:
`selectTextStyle:           ViewPropTypes.style,`
should be:
`selectTextStyle:            Text.propTypes.style`

I'll put in a pull request for it if this looks like a valid bug to you

**Comment by peacechen** [comment]
Hi @mienaikoe 
A PR would be fantastic.  Can `selectTextStyle` be both a string and style object?  If so, add both as an array to PropTypes.oneOfType

**Comment by mienaikoe** [comment]
hey @peacechen 

I think `selectTextStyle` can only be a style object. The string for the cancel text would be set on the `cancelText` prop.

I'll do a PR

**Comment by peacechen** [comment]
Merged. Thanks the the PR :+1:
