### ISSUE TITLE
Cancel button cut-off on Android

### ISSUE THREAD

**Issue by mienaikoe** [peacechen/react-native-modal-selector#27]
Hey again,

Have been noticing that the cancel button is cut off on Android: 
![cutoff](https://user-images.githubusercontent.com/3875239/30523731-7a88b2ca-9bb4-11e7-8151-3d0eb846e1b2.png)

I suspect it's due to the `maxHeight: 30` set at `style.js:29`. I tried commenting this out, and it looks fine on Android and iOS. Looking at the git blame, though, it looks like the reason this was added in has to do with portrait and landscape mode.

Would love for this to be changed, or the ability to override this in like a `cancelContainerStyle` property or something.

**Comment by mikaello** [comment]
Thanks for reporting this issue! 

Which version of android do you have?

Do you experience this cut off with many elements as well (filling more than the whole screen height)?

Does the removal of this height also look fine in landscape mode with both few and many elements?

Sorry for all the questions, but I have experienced different behavior with different settings.

**Comment by mienaikoe** [comment]
1) Android 5.0.1 / React-Native 
2) Yes, I am using 0.19
3) I don't see this cutoff anywhere else. The issue isn't that the modal is filling more than the screen height. You can see in the screenshot that the bottom of the cancel button is nowhere near the bottom of the screen
4) I can't test in landscape mode easily.

I have a feeling it may be due to my use of custom font. I'm using Lato globally in my app. This might bump up the lineHeight in some cases. I noticed you had a cancel button at fontSize 16, and the cancel padding was 8. A maxHeight of 30 infers that the cancel button would only work with those specific styles. Try upping the fontSize in the cancel button to emulate this.

**Comment by peacechen** [comment]
`cancelContainerStyle` sounds like the best option to let the user accommodate different font sizes & types.

**Comment by mikaello** [comment]
It seems a bit complicated to get the size of the `cancelContainer` right, so a `cancelContainerStyle`-prop seems like a good idea!

Here is some screenshots of different configurations on Android 7:
![close_sizes](https://user-images.githubusercontent.com/2505178/30537535-4cc10c64-9c6a-11e7-9d17-5097b563d8b1.png)

**Comment by reznik789** [comment]
I have the same issue? I fix this passing this props
`cancelTextStyle={{ fontSize: 18 }}`
`cancelStyle={{ padding: 2.5  }}`

**Comment by peacechen** [comment]
Nice solution using existing props, @reznik789 👍 

`cancelContainerStyle` would still be a useful additional to give the most flexibility, but that's not a blocker.

**Comment by tonygriv** [comment]
Yes, we need cancelContainerStyle to override maxHeight: 30 and so on!

**Comment by peacechen** [comment]
@tonygriv  Would you mind creating a PR?  We actively review and merge PR's on this project.

**Comment by tonygriv** [comment]
@peacechen https://github.com/peacechen/react-native-modal-selector/pull/41

**Comment by mikaello** [comment]
I agree that removing `maxHeight` could be an ok solution, but then `flexGrow` also have to be removed, or all the elements will float to the top (see screenshots above).
