### ISSUE TITLE
backdropPressToClose doesn't work

### ISSUE THREAD

**Issue by ziyafenn** [peacechen/react-native-modal-selector#33]
Hey there! First, thanks for the great fork. Work perfectly!

Just noticed that `backdropPressToClose={true}` does nothing.

Thanks!

**Comment by peacechen** [comment]
The latest version hasn't been published to npm.  I'll do that today, but if you need it immediately you can point your package.json directly to this repo.
```
  "react-native-modal-selector": "https://github.com/peacechen/react-native-modal-selector.git",
```

**Comment by peacechen** [comment]
published
