### ISSUE TITLE
How to remove border?

### ISSUE THREAD

**Issue by mobitinker** [peacechen/react-native-modal-selector#36]
Nice component! Thanks!

Is there a way to hide the border? I've tried as follows:

      <View style={styles.contLeftJustifiedRow}>
        <ModalSelector
          data={siteData}
          initValue={initVal}
          style={styles.contPicker}
          selectTextStyle={styles.fontPickerItem}
          onChange={(option)=>{ this.updateSite(option)}}
          cancelText={I18n.t('Cancel')}
          backdropPressToClose={true}
        />
      </View>
    )

  }
}

const styles = StyleSheet.create({
  ...appStyles,

  // Local styles
  contPicker: {
    borderWidth: 0,
    borderColor: Colors.background,
  },
.....

**Comment by peacechen** [comment]
I don't see a borderWith set in the base styles and can't discern one from looking at it.  Try the prop `optionContainerStyle`.  Would you post a screenshot (magnified?) showing where the border is?

**Comment by terohotti** [comment]
![image](https://user-images.githubusercontent.com/4482090/33133476-8cae8810-cfa5-11e7-8019-3b7b63f0978b.png)

Any idea how to get rid of the bottom border of the last item?

**Comment by peacechen** [comment]
This looks like it will need a code change.  `sectionStyle` has a bottom border and is applied to each section (aka option).
https://github.com/peacechen/react-native-modal-selector/blob/master/index.js#L120

One way to achieve that is to use map's index second parameter to detect the last item and remove the border.  For example:
```
let options = this.props.data.map((item, index => {
    if (item.section) {
        return this.renderSection(item);
    }
    renderOption (item, index === this.props.data.length - 1);
});
```

The renderOption signature would change to accept a second parameter:
```
renderOption(option, isLastItem) {
    return (
        <TouchableOpacity key={option.key} onPress={() => this.onChange(option)}>
]}>
            <View style={[styles.optionStyle, this.props.optionStyle, isLastItem &&
 {borderBottomWidth: 0}]}>
        ...
    );
}
```

**Comment by terohotti** [comment]
@peacechen I have now created a PR.  #38 

I needed to slightly modify your code to get it work. Tested it locally in my project and it worked fine!

**Comment by mikaello** [comment]
Merged and [new version](https://github.com/peacechen/react-native-modal-selector/releases/tag/0.0.22) in NPM
