### ISSUE TITLE
How to align the modal to the bottom of screen?

### ISSUE THREAD

**Issue by AfiyaA** [peacechen/react-native-modal-selector#37]
I am trying to align the modal selector with the bottom of the screen. Adding styling to optionContainerStyle prop works but fails for the cancelStyle prop. The cancel button stays in the middle of the screen where I want the cancel to be aligned with the bottom and teh optionContainer to show and expand upwards. Here is the code for my modal selector:
<ModalSelector
	cancelTextStyle={{color: '#007AFF', fontWeight: '500'}}
	cancelStyle={{ width: width - 30, position:'absolute', bottom: 0}}
        optionTextStyle={{color: '#586273', fontWeight: '500'}}
	optionContainerStyle={{width: width - 30, position:'absolute', bottom: 40}}
	data={this.state.modes}
	backdropPressToClose={true}
	overlayStyle={{backgroundColor:'rgba(0,0,0,0.8)'}}
	onChange={this.onModeSelect}>

Thanks!

**Comment by mikaello** [comment]
Try with `overlayStyle={{ justifyContent: flex-end }}`:

```jsx
<ModalSelector
    cancelTextStyle={{ color: '#007AFF', fontWeight: '500' }}
    cancelStyle={{ width: width - 30 }}
    optionTextStyle={{ color: '#586273', fontWeight: '500' }}
    optionContainerStyle={{ width: width - 30 }}
    data={this.state.modes}
    backdropPressToClose={true}
    overlayStyle={{ backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: flex-end }}
    onChange={this.onModeSelect}
>
```

**Comment by AfiyaA** [comment]
Thank you so much! Worked with a charm!!

**Comment by mikaello** [comment]
I'm glad it worked :-)
