### ISSUE TITLE
More than one TextInput on screen causes all text to dissapear

### ISSUE THREAD

**Issue by nhano0228** [peacechen/react-native-modal-selector#39]
When more than one textinput is present on screen, and the modal selector is used. All of the text is removed from the textinput, not just the textinput that is being used in conjunction with the modal selector.

**Comment by mikaello** [comment]
Would you mind telling a little more about your setup:
Which version of react-native?
Which version of react-native-modal-selector?
iOS or Android?

And could you copy paste a minimal working example? I tried to reproduce with the sample app and multiple TextInput fields, but I could not reproduce what you described.

But I did find a bug with the newest version of react-native-modal-selector (v0.0.22) in Android, I would post a fix soon, but that bug does not seem related to what you describe.

**Comment by nhano0228** [comment]
Sorry if I was unclear. I am using react-native 0.49 with react-native-modal-selector 0.0.22 on an iOS device.
Below is a code snippet as well as a gif showing what is going on:

![screen shot 2017-11-25 at 9 39 25 am](https://user-images.githubusercontent.com/20156150/33231528-93af473c-d1c4-11e7-8d38-20c57cef697b.png)

![b0643865-906d-4f42-be23-82294b50f233 1](https://user-images.githubusercontent.com/20156150/33231435-75b51de8-d1c3-11e7-841c-d8b3e1710f65.gif)

**Comment by peacechen** [comment]
Haven't been able to reproduce this.  The state of the other TextInputs should be independent of the picker's TextInput.  Is it possible you have another click handler that fires on modal interaction?

It would help if you posted source code from the rest of the page.  Please post as a text snippet instead of a bitmap.

**Comment by mikaello** [comment]
I made an [Expo snack](https://snack.expo.io/H1SAor3eM) where I tried to reproduce this, but still no luck. Feel free to copy and mody my snack or create a new one who could reproduce your bug.

**Comment by peacechen** [comment]
Thanks @mikaello 

I updated the snack to make the TextInputs more visible.
https://snack.expo.io/SJdt1Dnlz

**Comment by peacechen** [comment]
@nhano0228   We haven't been able to repro this (see snacks above).  If you can pinpoint it, feel free to re-open this issue.
