### ISSUE TITLE
Opacity option

### ISSUE THREAD

**Issue by joaom182** [peacechen/react-native-modal-selector#44]
There's any way to define opacity when touch on the elements? For example cancel button...

**Comment by mikaello** [comment]
If you mean like defining [`activeOpacity`](https://facebook.github.io/react-native/docs/touchableopacity.html#activeopacity) for `Touchable-`-components, so no, there is currently not such an option.

But you are free to open a PR for it if you think it should be a prop for this :-)

**Comment by mikaello** [comment]
This is now supported as of [v.0.0.26](https://github.com/peacechen/react-native-modal-selector/releases/tag/v0.0.26) with the `touchableActiveOpacity` prop
