### ISSUE TITLE
Adding testID prop

### ISSUE THREAD

**Issue by anovoselnik** [peacechen/react-native-modal-selector#47]
I have started using detox to test my app and I found out that testID prop is not passed to the component.

**Comment by anovoselnik** [comment]
Created PR #48

**Comment by peacechen** [comment]
Thanks for the PR.  I'm curious how detox expects to deal with the hundreds of RN components out in the wild that don't support `testID`.  I've not come across any other component that passes that through.  That doesn't seem to be a sustainable test approach.

**Comment by anovoselnik** [comment]
Well, I've found out that most of the components do ES6 spread of unknown props. Is that something we can do here also?

**Comment by anovoselnik** [comment]
Default React Native components have testID as a prop.
https://facebook.github.io/react-native/docs/button.html#testid

**Comment by mikaello** [comment]
This is now available as `passThruProps` in [v.0.026](https://github.com/peacechen/react-native-modal-selector/releases/tag/v0.0.26)
