### ISSUE TITLE
No SelectedIndex prop ?

### ISSUE THREAD

**Issue by yuvalkro** [peacechen/react-native-modal-selector#52]
Am I missing it ? 
how can I pre set the picker to show selected value on render?

**Comment by peacechen** [comment]
Currently there is no `selectedIndex` prop.  PRs are welcome if you would like to add the prop.  It should be a relatively easy addition.

**Comment by AnisDerbel** [comment]
I have never heard a selector component that doesn't have a selectedIndex!

**Comment by peacechen** [comment]
Now you have 😜 
The vast majority of use cases are for a user to make a new selection.  

Submit a PR and I'll merge it right away.

**Comment by peacechen** [comment]
Was looking through the code and the existing `initValue` prop may do what you want.
