### ISSUE TITLE
No change text Button cancel

### ISSUE THREAD

**Issue by namnn89** [peacechen/react-native-modal-selector#57]
Change text button cancel:
<ModalSelector
                                                data={this.state.cities}
                                                initValue="Select something yummy!"
                                                supportedOrientations={['landscape']}
                                                accessible={true}
                                                scrollViewAccessibilityLabel={'Scrollable options'}
                                                cancelButtonAccessibilityLabel={'Cancel Button'}
                                                onChange={(option)=>{ this.setState({textInputValue:option.label})}}>
        
                                                <TextInput
                                                    style={{borderWidth:1, borderColor:'#ccc', padding:10, height:30}}
                                                    editable={false}
                                                    placeholder="Select something yummy!"
                                                    value={this.state.textInputValue} />
    
                                            </ModalSelector>

i Try change text "Cancel" -> "Cancel Button" but not working

**Comment by smkamranqadri** [comment]
How do you resolve this?

**Comment by smkamranqadri** [comment]
it is cancelText prop which change the text.
