### ISSUE TITLE
Key/Label extractors of data blank labels

### ISSUE THREAD

**Issue by Diego-Fu** [peacechen/react-native-modal-selector#58]
I copy/paste the next example, but looks like the label is blank, i can get the data but is not showing on the modal.
```

this.setState({data: [{ id: 5, name: 'Red Apples' }]});

return (
  <ModalSelector
     data={this.state.data}
     keyExtractor= {(item) => item.id}
     labelExtractor= {(item) => item.name}/>
);
```

**Comment by sinapcs** [comment]
I had this problem too. this feature is added recently. I removed and installed it again then problem gone.

**Comment by peacechen** [comment]
@sinapcs  Did you revert to a prior version to get it working?  Thanks for testing this out

**Comment by Diego-Fu** [comment]
@sinapcs i did rm -rf node_modules and reinstall again, still not working ):

**Comment by jmscarpa** [comment]
Using the from master works (: keyExtractor are not available in 0.0.25

**Comment by sinapcs** [comment]
@Diego-Fu You are right. I forgot to say you should use Master branch.
npm install https://github.com/peacechen/react-native-modal-selector

**Comment by mikaello** [comment]
I updated this package to [v0.0.26](https://github.com/peacechen/react-native-modal-selector/releases/tag/v0.0.26) now, so you should be able to download [that version from NPM](https://www.npmjs.com/package/react-native-modal-selector) to use the key/label extractor feature.

**Comment by jmscarpa** [comment]
Thanks @mikaello !

**Comment by Diego-Fu** [comment]
Thanks @mikaello and @sinapcs !
