### ISSUE TITLE
Alert does not work in SampleApp for iOS

### ISSUE THREAD

**Issue by mikaello** [peacechen/react-native-modal-selector#6]
I have upgraded the SampleApp to RN 0.47 in branch [update-sample-app](https://github.com/peacechen/react-native-modal-selector/tree/update-sample-app), and it works fine in Android. But for iOS the button-modal does not work when clicking an option. The alert pops up and disappears immediately, and the modals stays visible. Then the whole app gets unresponsive, except that you can scroll the window:

![ios_alert](https://user-images.githubusercontent.com/2505178/29239998-31281af4-7f5c-11e7-91df-b3c84a6688da.gif)

This may be related to [issue #24 in dan's repo](https://github.com/d-a-n/react-native-modal-picker/issues/24) (at least the actual behaviour is the same).

**Comment by mikaello** [comment]
I have tried to figure out this bug, and it seems that this has something to do with Modal from react-native, e.g. if you add `alert('crash')` to the `onPress`-handler in the example on [Modal doc-page](https://facebook.github.io/react-native/docs/modal.html), you get the same behaviour (the app get unresponsive after the alert has shown and immediately dissapeared). I made an [Expo-snack](https://snack.expo.io/B1JRH9JdW) so you could test.

Android is fine though, no problem with alert and modal there.

**Comment by peacechen** [comment]
Thanks for researching this bug @mikaello .  I prefer not to put in band-aids for bugs in the framework (RN) unless absolutely necessary.  Let's see whether Facebook fixes it, or submit a PR to fix the underlying bug in RN.

**Comment by mikaello** [comment]
davidlongest refer to the modul [`react-native-modal`](https://github.com/react-native-community/react-native-modal), which is something in between [Modal](https://facebook.github.io/react-native/docs/modal.html) from react-native and this modul, i.e. it is `react-native-modal` that has the `onModalHide`-prop.

I also hope Facebook will fix it, but it may take some time, the issue is already almost a year old.

**Comment by peacechen** [comment]
Took a look at `react-native-modal` to see whether we could mimic its `onModalHide` feature.  It's not clear to me how he's able to call the animations through the `this.contentRef` reference.  Would it be worth adding that behavior to allow users of react-native-modal-selector to more easily deal with this RN bug?

**Comment by mikaello** [comment]
From what I can see, davidlongest is wrong and `react-native-modal` does not work with alert. Check out this Expo snack for a (non working) demo: https://snack.expo.io/S1RTQ7f_b

**Comment by peacechen** [comment]
Nice investigative work 👍 

Guess we're back square one with setTimer :(

**Comment by mikaello** [comment]
I have also tested `requestAnimationFrame`, with similar setup as [petersuwara](https://github.com/facebook/react-native/issues/10471#issuecomment-305407719) (with double/recursive `requestAnimationFrame`), but I could still reproduce the bug, but only at every 10 to 15 try or so. Since it wasn't stable, and I couldn't figure out the reason why, I just went with `setTimeout`, which I can reason about why would work.

**Comment by waynebloss** [comment]
Have you tried using `InteractionManager.runAfterInteractions` instead of `setTimeout`? Maybe you can call `onChanged` with it internally instead of having the developer use it in eveyr `onChanged` handler.

**Comment by mikaello** [comment]
`InteractionManager.runAfterInteractions` does not seem to work either. Tried with the SampleApp.
