### ISSUE TITLE
scroll back to top

### ISSUE THREAD

**Issue by itcurves** [peacechen/react-native-modal-selector#61]
Hi I just install the component. it is looking nice, but when I scroll in the list it scroll back to top automatically and won't let me select anything after the first display.

Am I missing something?

thanks in advance

**Comment by peacechen** [comment]
What was the problem?

**Comment by itcurves** [comment]
I had a timer running that change state of a view and whenever it changes it render the list too and scroll to top.

**Comment by bigkrys** [comment]
> I had a timer running that change state of a view and whenever it changes it render the list too and scroll to top.

hi,how do you resolve it??
