### ISSUE TITLE
Getting the selected value

### ISSUE THREAD

**Issue by ajibdeji** [peacechen/react-native-modal-selector#65]
Is there a way to get the selected value programmatically?

**Comment by peacechen** [comment]
Currently there is not.  It should be straight-forward to add a getter to return `state.selected`.  Would you mind creating a PR?

**Comment by mikaello** [comment]
This is now possible with the `getSelectedItem()`-method, available from v.0.0.29. See example of usage here: https://snack.expo.io/By06Wb-dX
