### ISSUE TITLE
Modal does not support landscape / horizontal view

### ISSUE THREAD

**Issue by mikaello** [peacechen/react-native-modal-selector#7]
It does not seem to work with landscape view of phone with RNMS (see also [issue 41 in old repo](https://github.com/d-a-n/react-native-modal-picker/issues/41)).

In theory it is as easy as adding `supportedOrientations={['portrait', 'landscape']}` to the Modal-component, and this works as long as the orientation is fixed, but if orientation is not fixed and you turn the phone the width is not recalculated because it depends on `const { width } = Dimensions.get('window')`, and that does not change when orientation changes. See discussion and possible workarounds in [react-native issue #25](https://github.com/facebook/react-native/issues/25). You can see the problem here (the screengif program is not perfect):
![rotate_700](https://user-images.githubusercontent.com/2505178/29262695-fc0003de-80d5-11e7-9110-ad9174c31a1b.gif)

A fix can be to use flex to adjust size instead of `Dimensions.get('window')`:
![rotate_fix](https://user-images.githubusercontent.com/2505178/29262930-f4656d66-80d6-11e7-93f4-8f6deaef8d9c.gif)

It seems to work on iOS simulator, but it should be tested on other devices as well. This attempt to fix horizontal view with flex can be tested in branch [support-for-landscape-view](https://github.com/peacechen/react-native-modal-selector/tree/support-for-landscape-view). Add this in package.json:
`"react-native-modal-selector": "peacechen/react-native-modal-selector#support-for-landscape-view"`

**Comment by peacechen** [comment]
That looks like a great solution. Thanks @mikaello

**Comment by peacechen** [comment]
@mikaello 
Do the other orientations ('portrait-upside-down', 'landscape-left', 'landscape-right') need to be added to `supportedOrientations` ?

RN Modal docs:
https://facebook.github.io/react-native/docs/modal.html

**Comment by mikaello** [comment]
I can't see any difference in iOS simulator between having `'portrait', 'landscape', 'portrait-upside-down', 'landscape-left', 'landscape-right'` or just `'portrait', 'landscape'`. But I am not sure about the implications of adding or avoiding those extra options.

But one thing I was thinking about adding, was a prop to `react-native-modal-selection`, so the user could force it in either portrait or landscape (and having both as default). This would only apply to iOS, since Android seem to ignore this prop.

**Comment by peacechen** [comment]
I agree, a prop would allow users to choose how they want ModalSelector to behave 👍
