### ISSUE TITLE
Style currently selected option differently

### ISSUE THREAD

**Issue by Kelvin9393** [peacechen/react-native-modal-selector#75]
Hi, is there a way for me to style the currently selected option different from others or am I missing something?

**Comment by mikaello** [comment]
You are not missing something, as of now there is no way to specify custom style for the selected element. [I made an attempt](https://github.com/mikaello/react-native-modal-selector/tree/add-prop-for-custom-styling-selected-element) to add this feature with a new prop `selectedItemTextStyle`. If this is what you are looking for I can create a PR.

**Comment by peacechen** [comment]
Thanks @mikaello 

There have been a few features added since the last release.  Think it's time to publish a new version?

**Comment by Kelvin9393** [comment]
Yes, it is. Thanks @mikaello

**Comment by mikaello** [comment]
@peacechen yes, I think it is time for a new version. I'm without computer until next week, but after that I could merge this new feature and release the next version.
