### ISSUE TITLE
Modal don't close on android

### ISSUE THREAD

**Issue by laurentmichel** [peacechen/react-native-modal-selector#76]
Hello,

The modal don't want to close on android when i try to update the state of my parent component.
Here is my code :

Children component :
``` javascript
<ModalSelector
            data={data}
            initValue="Référence dalle"
            cancelText={"Annuler"}
            animationType="none"
            onChange={item => {
              this.setState({ selected_item: item.key });
              this.props.setState("test", "test");
            }}
          />
```

Parent component :
``` javascript
  _setState(name, value) {
    console.log(name + " " + value);
    this.setState({ [name]: value });
  }
```
``` javascript
<InputSlabReference
              slab_ref={this.state.slab_ref}
              setState={this._setState}
/>
```

But if i do the following, it's working : 

``` javascript
<ModalSelector
            data={data}
            initValue="Référence dalle"
            cancelText={"Annuler"}
            animationType="none"
            onChange={item => {
              this.setState({ selected_item: item.key });
            }}
          />
```
Can somebody explain to me what I’m doing wrong?

Thanks :)

**Comment by peacechen** [comment]
I'm not sure what your use case is.  Are you trying to dismiss the modal from the parent? Is the parent resetting and you want the modal to dismiss?

There is a safety valve you can try: the `visible` prop.  The built-in modal opener button can still open the modal, so you may need to be creative with the initial value of `visible`.

**Comment by laurentmichel** [comment]
Hello,

Thank you for answer.

The problem is that the modal doesn't close when I select an item.
It's appear only on Android and when i try to update the state of my parent component.

In my children component, i render this : 
``` javascript
<ModalSelector
            data={data}
            initValue="Référence dalle"
            cancelText={"Annuler"}
            animationType="none"
            onChange={item => {
              this.setState({ selected_item: item.key });
              this.props.setState("test", "test");
            }}
          />
```
And in my parent component, i have :

**Comment by peacechen** [comment]
I see. You want to pass the selected value from child to parent.   Is `_setState` bound to the parent's context?  Its constructor should have:
```
  this. _setState = this. _setState.bind(this);
```

**Comment by laurentmichel** [comment]
Hello,

It's not working. The parent state is updated but the modal is still open.

**Comment by laurentmichel** [comment]
Ok. I found why this is not working.

[Link](https://github.com/moschan/react-native-simple-radio-button/issues/83)

**Comment by peacechen** [comment]
Good investigating.  Does that library have a conflict with the built-in React Native modal?  This library uses that internally.

I noticed this in the `react-native-simple-radio-button` source code:
```
if (Platform.OS === 'android') {
  UIManager.setLayoutAnimationEnabledExperimental && 
  UIManager.setLayoutAnimationEnabledExperimental(true);
}
```

Try to comment that out and see if it fixes your issue.

**Comment by laurentmichel** [comment]
Hello,

This is working when i comment these lines.

**Comment by luispeerez** [comment]
I have a similar issue with react-native-popup-dialog https://github.com/jacklam718/react-native-popup-dialog
The problem appear when I load a screen that contains a popup, the overlay opacity renders even when the popup is hidden. @peacechen Your solution worked, will try to make a pull request with those fixes to react-native-simple-radio-button

**Comment by peacechen** [comment]
@luispeerez  Thanks for confirming the fix.

If the `react-native-simple-radio-button` maintainer(s) aren't receptive to the PR. a prop to control the code block may be a compromise.  For example:
```
if ((Platform.OS === 'android') && this.props.useExperimentalAnimationAndroid) {
  UIManager.setLayoutAnimationEnabledExperimental && 
  UIManager.setLayoutAnimationEnabledExperimental(true);
}
```

The default value for that prop would be true to maintain current behavior.  You could then pass in `false` for that prop to get it to work for your situation.

**Comment by vitorsgomes** [comment]
I facing the same issue here, what I'm doing is to disable the animation until it gets fixed.
