### ISSUE TITLE
Hide the button 

### ISSUE THREAD

**Issue by cicer1** [peacechen/react-native-modal-selector#78]
Is there a way to hide the button itself? I want to open programmatically with my own flow

**Comment by peacechen** [comment]
This feature was added in #72 

It's available on master which you can use by pointing directly to this repo.  It will be part of the next npm release.

**Comment by mikaello** [comment]
[Version 0.0.28](https://github.com/peacechen/react-native-modal-selector/releases/tag/v0.0.28) is now released and contains this feature.
