### ISSUE TITLE
Setting numberOfLines

### ISSUE THREAD

**Issue by km147** [peacechen/react-native-modal-selector#85]
I would like to truncate the selected item text. Is there any way of setting the numberOfLines for it?

![device-2018-08-28-130215](https://user-images.githubusercontent.com/14110549/44721860-2459a700-aac3-11e8-853e-d4697a7341a5.png)

Would like the above to stay on a single line.

**Comment by peacechen** [comment]
The Text component in the option will need that prop added. 
https://github.com/peacechen/react-native-modal-selector/blob/master/index.js#L192

If you still need this, I propose adding `optionTextPassThruProps` to allow the user to add any props to the Text component that the like. As always, PRs are welcome so if you have time to take a stab at this, I'll merge it immediately.
