### ISSUE TITLE
setting initValue as icon

### ISSUE THREAD

**Issue by randomkrishna** [peacechen/react-native-modal-selector#86]
I want to set initValue as an icon and even after onChange it should be the same icon. How can I achieve this?

**Comment by randomkrishna** [comment]
I found the solution, we have to place our Icon in Text component then it works.
 `const rightIcon = <Text><FontAwesomeIcon name="menu" size={30} color="#fff" /></Text>;`
`<ModalSelector
        data={data}
        initValue={rightIcon}
/>`

**Comment by peacechen** [comment]
@randomkrishna 

Try using the icon directly.  For instance:
```
const rightIcon = <FontAwesomeIcon name="menu" size={30} color="#fff" />;
```
