### ISSUE TITLE
 Icons in the label inside the data array

### ISSUE THREAD

**Issue by JorgeMoralesLopez** [peacechen/react-native-modal-selector#98]
Is it possible to enter icons in the label inside the data array? I need to put several, I get one and two into an array but the app breaks and starts again when I select it ...
`const data = [{ key: index++, label:  [<Icon name="ios-man" key={1} size={34} />, <Icon name="ios-man" key={1} size={34} />]}]`
Magnificent bookstore, thank you!

**Comment by peacechen** [comment]
Currently the label must be a string.  This is where `labelExtractor` takes the value and puts it in a `Text` component:
https://github.com/peacechen/react-native-modal-selector/blob/master/index.js#L181

It would be relatively straight-forward to add a prop `componentExtractor` to support passing in custom components through a `component` key in the data set.

PRs are welcome.  Are you interested in adding this feature?

**Comment by JorgeMoralesLopez** [comment]
Hello @peacechen, thanks for the information! I have tried it as it says and it works perfectly.
Thank you very much for providing this great tool.

**Comment by JorgeMoralesLopez** [comment]
And how could I change the cancel string of the button?
cancelButtonAccessibilityLabel? I've tried it and it does not work...

**Comment by peacechen** [comment]
The cancel button's string can be changed with the `cancelText` prop.
https://github.com/peacechen/react-native-modal-selector#props

Thanks for testing the new feature.  I'll publish a new version on NPM soon.
